### ISSUE TITLE
How to deal with oda-api token in renku?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/renku-project-template#5]
I run my jobs being identified, this is particularly relevant for private data. 

How can I safely pass a token that needs to be renovated every few days to run a notebook inside renku without security issues ?

I have no idea, so I ask suggestions

**Comment by volodymyrss** [comment]
see how it's done here, the token is commented: https://renkulab.io/gitlab/astronomy/mmoda/mmoda-request/-/blob/mmoda_request_5ae54239b14c7cb2/api_code_5ae54239b14c7cb2.ipynb

**Comment by burnout87** [comment]
It was actually already discussed

https://github.com/oda-hub/smartsky/issues/58

**Comment by volodymyrss** [comment]
> It was actually already discussed
> 
> [oda-hub/smartsky#58](https://github.com/oda-hub/smartsky/issues/58)

yeah, but let's not confuse @ferrigno with this possible future renku feature. It is quite irrelevant to the current needs.

**Comment by ferrigno** [comment]
I have actually implemented it here 
https://renkulab.io/projects/carlo.ferrigno/oda-integral-spectrum/files/blob/isgri-spectrum.ipynb
It remains problematic if I want to run periodically a notebook (provided that this is possible)

**Comment by volodymyrss** [comment]
oda_api should then use getpass as a fall-back if allowed, and otherwise use variable like now. then all cases will work
